# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usrname', models.CharField(max_length=30, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u90ae\u7bb1')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('admin_type', models.IntegerField(choices=[(0, '\u666e\u901a\u7528\u6237'), (2, '\u666e\u901a\u7ba1\u7406\u5458'), (3, '\u8d85\u7ea7\u7ba1\u7406\u5458')], default=0, verbose_name='\u7528\u6237\u7c7b\u578b')),
                ('balance', models.FloatField(default=0, verbose_name='\u8d26\u6237\u4f59\u989d')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
